apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeeapp-deployment
  labels:
    app: employeeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employeeapp
  template:
    metadata:
      labels:
        app: employeeapp
    spec:
      containers:
      - name: springserver
        image: hugojesusmr/employee:latest
        ports:
        - containerPort: 8080
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  selector:
    app: employeeapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8080
    nodePort: 31110